### ISSUE TITLE
continue bug when counting domains

### ISSUE THREAD

**Issue by robgjansen** [privcount/privcount#479]
When counting domains, I used the following config:

```json
tally_server:
    counters: 'domain.counters.yaml'
    noise: 'domain.counters.yaml' # will regen sigmas, use `sigmas:` to avoid
    allocation: 'round1-8.allocation.yaml'

    domain_files: # top level domains
        - 'domains/tld/domain-torproject.txt'
        - 'domains/tld/tld-com-20171221.txt'
        - 'domains/tld/tld-net-20171221.txt'
        - 'domains/tld/tld-org-x-torproject-20171221.txt'
        - 'domains/tld/tld-ru-20171221.txt'
        - 'domains/tld/tld-de-20171221.txt'
        - 'domains/tld/tld-br-20171221.txt'
        - 'domains/tld/tld-jp-20171221.txt'
        - 'domains/tld/tld-uk-20171221.txt'
        - 'domains/tld/tld-it-20171221.txt'
        - 'domains/tld/tld-in-20171221.txt'
        - 'domains/tld/tld-fr-20171221.txt'
        - 'domains/tld/tld-cn-20171221.txt'
        - 'domains/tld/tld-ir-20171221.txt'
        - 'domains/tld/tld-pl-20171221.txt'

    sk_threshold: 3
    dc_threshold: 16
    continue: 1

    listen_port: 33333 # this is open on the firewall
    checkin_period: 600 # 10 minutes
    collect_period: 86400 # 1 day
    delay_period: 86400 # 1 day
    event_period: 300 # 5 mins
    circuit_sample_rate: 1.0

    noise_weight:
        # we are using an operator model, where we assume that
        # at least one operator is not untrusted. each operator's
        # contribution to the noise should be 'spread out'
        # over the relays they operate, such that the total
        # of the squares for that operators weights sum to 1.
        # Tim : sqrt(1/7) = 0.377964473
        '068308AD070849A71B8C1DB06C2509E82C40B908': 0.377964473
        '1A4488A367D89D0EFDA88116059FEBCACF0F508A': 0.377964473
        '363F42695F2DD825DA5A4E6ABF3FBDFCFD1E9AE2': 0.377964473
        'A5945077E0D35729F8E2920A54BE12A0058B403E': 0.377964473
        'B6718125C43ECA2E5011B3C681BB6638617A9686': 0.377964473
        'C6B3546CC6BCCB649FEC82D348D464554BC6323D': 0.377964473
        'DE684E6C6B7773B8BE74B4D941E4178988E15E26': 0.377964473
        # Rob : sqrt(1/4) = 0.5
        '0DA9BD201766EDB19F57F49F1A013A8A5432C008': 0.5
        '12B80ABF019354A9D25EE8BE85EB3C0AD8F7DFC1': 0.5
        'C170AE5A886C5A09D6D1CF5CF284653632EEF25D': 0.5
        '4B1E3276137AD12DCCEBE354EA11C1E47F804F67': 0.5
        # Matt : sqrt(1/5) = 0.447213595
        '09FA8B4F665AD65D2C2A49870F1AA3BA8811E449': 0.447213595
        '335746A6DEB684FABDF3FC5835C3898F05C5A5A8': 0.447213595
        '98D10461F6EDF13780D20D7E402E67F40C5ADBD9': 0.447213595
        'D53793315E290D250E9AFC431A4C9068A1E53C98': 0.447213595
        '91516595837183D9ECD1318D00723A8676F4731C': 0.447213595
```

After the collection finished, I changed the config as follows:

```diff
-    domain_files: # top level domains
-        - 'domains/tld/domain-torproject.txt'
-        - 'domains/tld/tld-com-20171221.txt'
-        - 'domains/tld/tld-net-20171221.txt'
-        - 'domains/tld/tld-org-x-torproject-20171221.txt'
-        - 'domains/tld/tld-ru-20171221.txt'
-        - 'domains/tld/tld-de-20171221.txt'
-        - 'domains/tld/tld-br-20171221.txt'
-        - 'domains/tld/tld-jp-20171221.txt'
-        - 'domains/tld/tld-uk-20171221.txt'
-        - 'domains/tld/tld-it-20171221.txt'
-        - 'domains/tld/tld-in-20171221.txt'
-        - 'domains/tld/tld-fr-20171221.txt'
-        - 'domains/tld/tld-cn-20171221.txt'
-        - 'domains/tld/tld-ir-20171221.txt'
-        - 'domains/tld/tld-pl-20171221.txt'
+    #domain_files: # popularity
+        - 'domains/pop/domain-torproject.txt
+        - 'domains/pop/domain-top-10-20171221.txt'
+        - 'domains/pop/domain-11-100-20171221.txt'
+        - 'domains/pop/domain-101-1000-20171221.txt'
+        - 'domains/pop/domain-1001-10000-20171221.txt'
+        - 'domains/pop/domain-10001-100000-x-torproject-20171221.txt'
+        - 'domains/pop/domain-100001-1000000-20171221.txt'

-    continue: 1
+    continue: 2
```

The logs indicate that the new domain files were correctly loaded by the TS, but then the TS immediately attempted to start the next round even though the delay period (24 hours) had not passed yet.

Here is the contents of `domain.counters.yaml` (which I did not change between rounds):

```yaml
counters:
  ExitDomainSuffixMatchWebInitialStreamCountList:
    bins:
    - - 0.0
      - 1.0
    - - 1.0
      - .inf
    epsilon: 0.21436910499649742
    estimated_value: 1238361.6
    expected_noise_ratio: 0.017804765585897664
    sensitivity: 400.0
    sigma: 12729.84481877006
  ExitHostnameWebInitialStreamCount:
    bins:
    - - -.inf
      - .inf
    epsilon: 0.0856291592801487
    estimated_value: 1547952.0
    expected_noise_ratio: 0.017804765585897664
    sensitivity: 200.0
    sigma: 15912.306023462575
privacy:
  delta: 1.0e-11
  epsilon: 0.3
  epsilon_tolerance: 1.0e-15
  excess_noise_ratio: 3
  sigma_ratio: 0.017804765585897664
  sigma_ratio_tolerance: 1.0e-06
  sigma_tolerance: 1.0e-06
```
